import type { ReactNode } from "react";
import { SidebarTrigger } from "@/components/ui/sidebar";
import { Separator } from "@/components/ui/separator";

interface AppShellProps {
  title: string;
  description?: string;
  icon?: ReactNode;
  actions?: ReactNode;
  children: ReactNode;
}

export function AppShell({ title, description, icon, actions, children }: AppShellProps) {
  return (
    <div className="flex min-h-screen flex-1 flex-col">
      <header className="sticky top-0 z-20 flex h-14 items-center gap-3 border-b bg-background/80 px-4 backdrop-blur md:px-6">
        <SidebarTrigger />
        <Separator orientation="vertical" className="h-5" />
        <div className="flex min-w-0 items-center gap-2">
          {icon}
          <h1 className="truncate text-sm font-semibold sm:text-base">{title}</h1>
        </div>
        <div className="ml-auto flex items-center gap-2">{actions}</div>
      </header>
      <main className="flex-1 px-4 py-6 md:px-8 md:py-8">
        <div className="mx-auto w-full max-w-6xl">
          {description ? (
            <p className="mb-6 max-w-3xl text-sm text-muted-foreground">{description}</p>
          ) : null}
          {children}
        </div>
      </main>
      <footer className="border-t bg-muted/30 px-4 py-3 md:px-8">
        <p className="mx-auto max-w-6xl text-[11px] leading-relaxed text-muted-foreground">
          <span className="font-medium text-foreground">Responsible AI notice:</span> Outputs are
          generated by an AI model and may be inaccurate or incomplete. Review and edit results
          before sharing, sending, or acting on them. Do not paste confidential or regulated
          information.
        </p>
      </footer>
    </div>
  );
}
